[book]
title = "序数理论手册"
language = "zh"
src = "src"

[build]
build-dir = "build"
create-missing = false

[output.html]
cname = ""
default-theme = "coal"
git-repository-url = ""
preferred-dark-theme = "coal"

[output.linkcheck]
