[book]
title = "序数理论手册"
language = "zh"
src = "src"

[build]
build-dir = "build"
create-missing = false

[output.html]
cname = "drjinglee.github.io"
default-theme = "coal"
git-repository-url = "https://github.com/DrJingLee/DrJingLee.github.io"
preferred-dark-theme = "coal"

[output.linkcheck]
